Add hotjar javascript link
safe-global/safe-homepage pull request #220
Opened 2023-07-27 13:04 UTC by danielpartida

UX team would like to have heatmaps, i.e. see what users click, what users are missing from our landing page

Documentation of Hotjar [here](https://www.notion.so/safe-global/Set-up-Hotjar-b3b848371f9a4ac7bbd21e7f88b5f42f)

2023-07-27 13:19 UTC, katspaugh commented
@danielpartida I've changed the script tag a bit for it to be React-compatible.

2023-07-27 13:25 UTC, iamacook commented on src/pages/_document.tsx
> +          {IS_PRODUCTION && (
```suggestion
          {IS_PRODUCTION && IS_OFFICIAL_HOST && (
```

Need we also add this to the `ContentSecurityPolicy`?

2023-07-27 13:26 UTC, katspaugh commented on src/pages/_document.tsx
> +          {IS_PRODUCTION && (
AFAICS, we have neither this variable nor CSP in this repo.

2023-07-27 13:43 UTC, iamacook commented on src/pages/_document.tsx
> +          {IS_PRODUCTION && (
Very true, I thought we were in another one 🙈

2023-08-02 12:12 UTC, usame-algan requested changes
We need to make sure that the Hotjar script is only included if the analytics cookie is set / was accepted

2023-08-07 13:48 UTC, katspaugh commented on src/pages/_document.tsx
> +              <script defer data-domain="safe.global" src="https://plausible.io/js/script.js" />
Could you also remove this? We decided not to go with it.
cc @danielpartida

2023-08-07 13:51 UTC, DiogoSoaress commented on src/pages/_document.tsx
> +              <script defer data-domain="safe.global" src="https://plausible.io/js/script.js" />
removed

2023-08-08 07:44 UTC, katspaugh requested changes
I cannot test it because it's only enabled if IS_PRODUCTION. Please remove the flag temporarily.

Also I assume Hotjar uses cookies (since we ask for a cookie consent to enable it) but the Cookie Policy only mentions GA.

2023-08-08 09:38 UTC, DiogoSoaress commented
> I cannot test it because it's only enabled if IS_PRODUCTION. Please remove the flag temporarily.

I am temporarily modifying the `deploy` workflow to deploy this branch to the staging environment. Reason being it is the corresponding domain of `NEXT_PUBLIC_HOTJAR_ID_STAGING`.

2023-08-08 10:06 UTC, katspaugh commented
I still don't see hotjar loaded. You need to pass the new secrets to the build here: https://github.com/safe-global/safe-homepage/blob/main/.github/workflows/build/action.yml#L20-L21

Please don't ask me for a review until you have verified yourself that it works.

2023-08-08 13:49 UTC, DiogoSoaress commented
I will block this PR until we have assessed the Cookie Policy update.

2023-08-29 08:44 UTC, DiogoSoaress commented on src/hooks/useHotjar.ts
> +      scriptRef.innerText = `(function(h,o,t,j,a,r){h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};h._hjSettings={hjid:${ID},hjsv:${HOTJAR_VERSION}};a=o.getElementsByTagName('head')[0];r=
I had to set the `script.innerText` so the installation could be verified on Hotjar's website

2023-08-29 08:45 UTC, DiogoSoaress commented
The changes in `.github/workflows/deploy.yml` will be reverted before merging the PR.
These changes currently serve the purpose of verifying the successful installation of Hotjar in `https://safe-web-landing.staging.5afe.dev/`

2023-08-29 08:57 UTC, katspaugh commented
The hotjar script is loaded when I accept analytics cookies but I don't see any events sent to hotjar afterwards.

Also there's an error in the console:

<img width="1469" alt="Screenshot 2023-08-29 at 10 54 55" src="https://github.com/safe-global/safe-homepage/assets/381895/1d27ae9f-b665-4097-a03a-ca10d38cd97c">

2023-08-29 11:12 UTC, DiogoSoaress commented
> Also there's an error in the console

Are you testing in https://safe-web-landing.staging.5afe.dev/ ??

> The hotjar script is loaded when I accept analytics cookies but I don't see any events sent to hotjar afterwards.

I just set up a Heatmap and it was successfully recorded. I also see Hotjar populating my Cookie storage
<img width="206" alt="Screenshot 2023-08-29 at 13 12 04" src="https://github.com/safe-global/safe-homepage/assets/32431609/5e8ad2ee-32af-4fd5-b57d-ffa12a9aa91d">

2023-08-29 11:19 UTC, katspaugh commented
I see no errors now and a working websocket connection. ✅

2023-08-29 11:21 UTC, katspaugh approved these changes
LGTM.

Don't forget to restore deploy.yml. On that note, you might want to introduce a third permanent branch (e.g. `feature`) that always deploys to dev and always name your PR branches `feature`.

2023-08-29 14:03 UTC, merged