feat: Preserve search parameters in external links
safe-global/safe-homepage pull request #258
Opened 2023-12-12 10:56 UTC by DiogoSoaress

## What it solves

We want to preserve the search parameters when navigating the homepage.

## How this PR fixes it

On page navigation the search parameters are merged and stored in the session storage key `SAFE__searchParams` and saved to a Context.
All links navigating to https://app.safe.global include the stored search parameters.

2023-12-12 10:58 UTC, DiogoSoaress commented
I would extend this behaviour to the other links in the homepage if you could navigate to a campaign page from https://safe.global , otherwise I don't see a justification to attach campaign related UTM codes when navigating to https://app.safe.global/

2023-12-12 11:52 UTC, katspaugh commented
* I would do it for all pages, not just campaigns
* Store the initial UTM params in the session storage so that they aren't gone on page refresh
* Why create a new component? You could just add it directly to ExternalLink.
* Next.js has a hook to get parsed params, which AFAIK is now preferred to useRouter, check out https://nextjs.org/docs/app/api-reference/functions/use-search-params

2023-12-13 10:23 UTC, DiogoSoaress commented
> I would do it for all pages, not just campaigns
Why?

> Store the initial UTM params in the session storage so that they aren't gone on page refresh
The search params are not lost on page refresh. This approach is however necessary if we want to hydrate the links on all pages with the UTM params, right?

2023-12-13 10:41 UTC, katspaugh commented
Because the user can:

1. come to a campaign page from a twitter link
2. navigate to another page on the site
2a. (potentially refresh the page)
3. only then go to app.safe.global

We lose the UTM params on steps 2 and 2a in your current implementation.

2023-12-13 11:07 UTC, DiogoSoaress commented
To clarify on the campaigns navigation:

* the user cannot reach the campaigns from safe.global and only the buttons in the campaign page link to the custom /welcome route in app.safe.global. The links on other pages link to https://app.safe.global, see https://safe.global/wallet for example.

- if you are in the current implementation with the UTM params shared on Twitter https://safe-web-landing.dev.5afe.dev/campaigns/social-login-gnosis?utm_source=t.co&utm_medium=cpc&utm_campaign=seedlessv1 and refresh the page, the search params are preserved.

Am I missing / overlooking something?

2023-12-13 11:25 UTC, katspaugh commented
Once again: the user can navigate to another internal page from the campaign page (e.g. via the links in the footer), at which point UTM params are lost.
I just don't see the point of limiting this solution to one particular type of pages while also making it less robust.

2023-12-13 11:33 UTC, katspaugh commented
I'll outline again my proposed solution which I shared before you started working on this PR:

* On page load, in a global context, save UTM params into the context and sessionStorage.
* Also attempt to restore any existing params from sessionStorage in case they are not in the URL.
* For all app.safe.global links, read UTMs from the global context and append them to the URL.

If you still disagree, please clarify the requiements with BI and marketing.

2023-12-14 07:38 UTC, katspaugh requested changes
Importing the context, the append function and calling said function for every link in every component with external links isn’t very maintainable don’t you think? Please propose an alternative solution to discuss.

The context needs tests.

2023-12-14 08:48 UTC, DiogoSoaress commented
> Please propose an alternative solution to discuss.

I think having a HOC to call the context and append the search params is more maintainable, avoiding all the duplicated code.
You mentioned above to use the `ExternalLink` component but we don't have that component in this repo so I need to create a new component for this purpose. WDYT?

2023-12-14 08:55 UTC, katspaugh commented
I don't see the need for a HoC. Just create a custom link component, e.g. `SafeLink` that has all the logic and renders a Link.

2023-12-14 14:50 UTC, katspaugh commented on src/components/common/SafeLink/index.tsx
> +    <Link href={finalHref} target="_blank" rel="noreferrer">
We should remove `rel="noreferrer"` for app.safe.global links.

2023-12-14 14:50 UTC, katspaugh commented on src/components/common/SafeLink/index.tsx
> +  const finalHref = appendSearchParamsToURL(href, searchParams)
`useMemo` perhaps?

2023-12-14 14:52 UTC, katspaugh commented
Looks good to me.

@usame-algan could you also take a look when you have a minute?

2023-12-14 15:09 UTC, usame-algan approved these changes
Looks good 👍 

I assume we use `SafeLink` for all links to `app.safe.global` but haven't checked each occurence.

2023-12-14 15:09 UTC, usame-algan commented on src/components/Campaign/Hero/styles.module.css
> +  width: fit-content;
nit: Not sure if this is needed. The button looks the same to me with or without this css.

2023-12-14 15:27 UTC, DiogoSoaress commented on src/components/Campaign/Hero/styles.module.css
> +  width: fit-content;
<img width="468" alt="Screenshot 2023-12-14 at 16 26 43" src="https://github.com/safe-global/safe-homepage/assets/32431609/a02c66fa-2f9b-4914-bafa-3ea811569225">

vs 

<img width="518" alt="Screenshot 2023-12-14 at 16 26 51" src="https://github.com/safe-global/safe-homepage/assets/32431609/ee6715a8-4f42-4746-b698-f70cc6344e70">

2023-12-14 15:28 UTC, DiogoSoaress commented on src/components/Campaign/Hero/styles.module.css
> +  width: fit-content;
The button keeps the width. It affects the link clickable area

2023-12-14 15:35 UTC, DiogoSoaress commented
> Launch Wallet button in the header it doesn't seem to be used

I've included it inside of the ContextProvider. Good catch @usame-algan

2023-12-14 15:47 UTC, katspaugh approved these changes
Thanks Diogo.
In future reviews we should keep in mind that we should always use SafeLink instead of Link for all links except when 100% internal.

2023-12-14 15:50 UTC, DiogoSoaress commented
Definitely!
I am very curious to see how carrying the UTM parameters will give another dimension to our website and wallet app traffic.

2023-12-14 15:50 UTC, merged