feat: 🎸 Add Industry Comparison Section
safe-global/safe-homepage pull request #427
Opened 2024-07-30 10:30 UTC by Malayvasa

Related to #381

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +    }
Due to the dependencies, I'd suggest we move memoise these in `useCallback`s.

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +      if (canvasRef.current && containerRef.current) {
Is `canvasRef.current` required for the mouse position? The value isn't used inside the handler.

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +      if (scrollYProgress && isMobile && containerRef.current) {
We could use early returns here to reduce indentation, e.g.
```suggestion
      if (canvasRef.current && containerRef.current) return
      const rect = containerRef.current.getBoundingClientRect()
      setMousePosition({ x: e.clientX - rect.left, y: e.clientY - rect.top })
    }

    const updateMobileMousePosition = () => {
      if (scrollYProgress && isMobile && containerRef.current) return
```

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +      requestAnimationFrame(lerpMousePosition)
We need to clean this up with `cancelAnimationFrame` on unmount.

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +  }, [mousePosition.x, mousePosition.y, containerRef, isMobile, scrollYProgress, dimensions.width])
There's a lot going on here in one `useEffect`. If it's possible, breaking it down would be ideal. Memoising the methods in `useCallback`s would help.

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +    }
Afaiu, this is related to drawing the dots? Could we locate them together?

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/utils/updateCanvasDimensions.ts
> +  containerRef: React.RefObject<HTMLDivElement>,
Instead of passing the ref, I think we can use the element directly, e.g.
```suggestion
  canvas: HTMLCanvasElement,
  container: HTMLDivElement,
```

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/IndustryComparison/utils/updateCanvasDimensions.ts
> +}
I'd suggest we split this - it's updating the canvas, but also getting the dimensions of the container (used in the component). I'd suggest we have two functions: something like `getContainerDimensions` (and maybe we don't need to store that in state) and then a function to update the canvas.

2024-08-05 15:05 UTC, DiogoSoaress requested changes

2024-08-15 09:33 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/styles.module.css
> +  line-height: 88px;
You can delete the class. Why do you need the `z-index` here?

2024-08-15 14:31 UTC, DiogoSoaress requested changes
Detected some causes of performance issues

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/utils/drawDots.ts
> +    const scale = Math.max(1, maxScale - distance / MAX_SCALE_DISTANCE)
Do you think this effect is relevant in mobile?

I even question if at all. If you are scrolling through the page, without anything to click, you don't even move the mouse 😅

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +        drawDots(ctx, dots, dimensions, mousePosition, isMobile)
This function is expensive to be called non-stop. Can you only redraw the dots when necessary? (i.e, when the mouse moves or when the resolution change)

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +        drawDots(ctx, dots, dimensions, mousePosition, isMobile)
Can you also explore a way to not have to draw the whole grid when the mouse moves but only the dots that are changing size?

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/utils/createDots.ts
> + */
The JSDOC needs to be right above the function declaration. Otherwise it is useless. You can check it by hovering any call to `createDots` in your IDE

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/styles.module.css
> +  }
This is the Typography's variant `h1`. You can remove the `.title` class

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/Content.tsx
> +  const opacityParams = [0.25, 0.35, 0.65, 0.75]
Aren't these the scrollParams?

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/Content.tsx
> +  const opacity = useTransform(scrollYProgress, opacityParams, [0, 1, 1, 0])
```suggestion
  const opacity = useTransform(scrollYProgress, scrollParams, opacityParams)
```

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +    updateCanvas(canvas, ctx, dimensions.width, dimensions.height)
This is also being called unconditionally without any change in the dimensions.

2024-08-15 14:31 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/utils/useMousePosition.ts
> +
```suggestion
```

2024-08-19 13:28 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +    updateCanvas(canvas, ctx, dimensions.width, dimensions.height)
How did you address it ? `drawDots` still being called unconditionally at every possible frame and updating the canvas context for every dot

2024-08-19 13:29 UTC, DiogoSoaress commented on src/components/DataRoom/IndustryComparison/DotGrid.tsx
> +        drawDots(ctx, dots, dimensions, mousePosition, isMobile)
How did you address it?

2024-08-19 13:32 UTC, DiogoSoaress requested changes
There are still some performance considerations:
- The animation loop runs continuously, which can be CPU-intensive. Consider adding throttling or debouncing if the animation doesn't need to run at the highest possible frame rate.

- Canvas Updates: The canvas is updated on every frame. Ensure that `drawDots` function is optimized to minimize the amount of work done per frame.

2024-08-20 13:48 UTC, DiogoSoaress approved these changes

2024-08-20 13:49 UTC, merged