feat: 🎸 Add See More Section
safe-global/safe-homepage pull request #428
Opened 2024-07-30 12:52 UTC by Malayvasa

Related to #384

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/SeeMore/Wave.tsx
> +  }, [])
Nit: let's move this to a custom hook. We could make it reusable and return the width _and_ height.

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/SeeMore/Wave.tsx
> +      requestRef.current = requestAnimationFrame(animate)
We don't need to use a ref for this. We can use a local variable.

2024-08-05 16:14 UTC, DiogoSoaress commented on src/components/DataRoom/SeeMore/index.tsx
> +  const opacitText = useTransform(scrollYProgress, [0, 0.3, 0.5, 0.75], [0, 1, 1, 0])
```suggestion
  const textOpacity = useTransform(scrollYProgress, [0, 0.3, 0.5, 0.75], [0, 1, 1, 0])
```

2024-08-05 16:14 UTC, DiogoSoaress commented on src/components/DataRoom/SeeMore/styles.module.css
> +}
Can't this be the same class?

2024-08-05 16:14 UTC, DiogoSoaress commented on src/components/DataRoom/SeeMore/styles.module.css
> +  }
Same class

2024-08-05 16:14 UTC, DiogoSoaress commented on src/hooks/useContainerSize.ts
Isn't this hook achieving the same as your other PR? https://github.com/safe-global/safe-homepage/pull/427/files#diff-e2177b83efbc74640ebcdbe372bcab4c7a8ddc7bc30f8b3dfce99761fdb54ad0

2024-08-12 10:23 UTC, DiogoSoaress approved these changes
Good job! There is one last comment but it should be good to merge after

2024-08-12 10:23 UTC, DiogoSoaress commented on src/components/DataRoom/SeeMore/Wave.tsx
> +        pathElement.setAttribute('d', `M${path}`)
I am having a runtime error coming from this line
<img width="428" alt="Screenshot 2024-08-12 at 12 22 25" src="https://github.com/user-attachments/assets/63d12d68-8616-4ad6-9d0d-1bd9c77e5e11">

2024-08-15 15:29 UTC, DiogoSoaress requested changes
I was also observing huge CPU usage in this branch and in the `Wave.tsx` file the sin computation and rendering is running as fast as possible the whole time…. We should try to only compute once the sin waves values or load them from a JSON file

2024-08-20 08:30 UTC, DiogoSoaress requested changes
Some leftovers

2024-08-20 11:44 UTC, DiogoSoaress approved these changes

2024-08-20 13:41 UTC, merged