feat: 🎸 Add Cexes Comparison Section
safe-global/safe-homepage pull request #429
Opened 2024-07-30 15:41 UTC by Malayvasa

Related to #382

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/Cexes/Cex.tsx
> +      {[...Array(boxes)].map((_, index) => (
Nit: to save the spread, we can instantiate the array with the length of `boxes`, e.g.
```suggestion
      {Array.from({ length: boxes },.map((_, index) => (
```

2024-07-31 08:58 UTC, iamacook commented on src/components/DataRoom/Cexes/Cex.tsx
> +}
Nit: I'd add the type to these from `motion.div` for safety.

2024-08-02 15:21 UTC, DiogoSoaress reviewed
Can you rename the folder -> `AssetsSecured`

2024-08-02 15:21 UTC, DiogoSoaress commented on src/content/dataroom.json
> +    "label": "CEX",
You can use `caption` here

2024-08-02 15:26 UTC, DiogoSoaress commented
Why aren't you fetching the values dynamically?

2024-08-06 08:17 UTC, DiogoSoaress commented
>when we had discussed on how we divide the work I was to implement the sections with static data and not look at the data fetching logic

That was indeed the agreement when we were developing V1 so you could concentrate on the animations. Data fetching is already implemented (you even used it for the WorldGDP implementation https://github.com/safe-global/safe-homepage/pull/418/files#diff-b538657fbd34189db0dce0f876fd3eef4d53835bcd82a64539c37608e62adfa8) 

What I am asking is for you to pull the real values from that [useSafeDataRoomStats](https://github.com/safe-global/safe-homepage/blob/main/src/hooks/useSafeDataRoomStats.ts) hook.

2024-08-07 16:22 UTC, DiogoSoaress requested changes
Almost there! Great job on the animation 👏 

Didn't we agree to put the scale factor in the top right corner? "1square = x Billion $" like in the next section

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getNormalizationFactor.ts
> +  tvlSafe: number | null,
I think this function should simply receive an array of numbers. We should need to change it if we want to add/remove one of the CEXes

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getTvlValue.ts
IMO we don't need this function

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/Cex.tsx
> +  id: string
Why do we need an id when you have a `name` ?

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/index.tsx
> +                normalizationFactor={normalizationFactor}
WDYT of passing the nrSquares?

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
`direction` is an invalid property

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
`direction` is an invalid property

2024-08-07 16:22 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
Could this be a flex box with gap `22px` ?

2024-08-07 16:22 UTC, DiogoSoaress commented on src/content/dataroom.json
> +        "boxColor": "var(--mui-palette-primary-light)",
I don't think we should be passing the CSS variable in the JSON file. Set a `primary` boolean and then conditionally resolve to the green color in the `<CEX>` component

2024-08-09 13:16 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
From Figma

2024-08-09 13:34 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/index.tsx
> +                normalizationFactor={normalizationFactor}
I was thinking if we could pass one less prop to the CEX component but `tvl` needs to be passed anyway because it is used besides the `nrBoxes` calculation.

2024-08-09 13:37 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
![Screenshot 2024-08-09 at 15 36 14](https://github.com/user-attachments/assets/765a0563-3533-42ef-8bed-1da8b40d0e10)

2024-08-09 13:55 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getNormalizationFactor.ts
> +const MAX_WIDTH = 648
I am asking to address this overflow by passing the `maxWidth` as a variable

<img width="1056" alt="Screenshot 2024-08-09 at 15 44 28" src="https://github.com/user-attachments/assets/8876cdb3-8f64-47b3-acb3-dc0f4844f7c2">

2024-08-09 13:56 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getNormalizationFactor.ts
> +const MAX_WIDTH = 648
You can create a custom hook `useViewportWith`

``` typescript
const [viewportWidth, setViewportWidth] = useState(window.innerWidth)

useEffect(() => {
  const handleResize = () => {
    setViewportWidth(window.innerWidth)
  }
  
  window.addEventListener('resize', handleResize)
  
  return () => {
    window.removeEventListener('resize', handleResize)
  }
}, [])
```

2024-08-09 15:30 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getNormalizationFactor.ts
> +const MAX_WIDTH = 648
I've addressed this in https://github.com/safe-global/safe-homepage/pull/429/commits/4fdf71f8776d1abdd7a1ae7185d3719ba15afbd0

2024-08-09 15:30 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getTvlValue.ts
Addressed in https://github.com/safe-global/safe-homepage/pull/429/commits/4c9abca8522226099cdcdc2f6fbfe2b5fd56edd1

2024-08-09 15:30 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/utils/getNormalizationFactor.ts
> +  tvlSafe: number | null,
Addressed in https://github.com/safe-global/safe-homepage/pull/429/commits/4c9abca8522226099cdcdc2f6fbfe2b5fd56edd1

2024-08-12 09:26 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +  const transformRTL = useTransform(scrollYProgress, [0.5, 0.75], ['0', '-100%'])
Aren't these variables named the other way around? `transformLTR` I see it's used to slide the content from Left to Right

2024-08-12 09:40 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +  const transformRTL = useTransform(scrollYProgress, [0.5, 0.75], ['0', '-100%'])
I misinterpreted. Thanks for clarifying

2024-08-12 09:58 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +        <Typography variant="h5">1 square - ${squareRatio.toFixed(2)}B</Typography>
Please use the existing formatter https://github.com/safe-global/safe-homepage/blob/main/src/lib/formatCurrency.ts

2024-08-12 09:58 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +  const squareRatio = normalizationFactor / 1000000000
Why do you need this?

2024-08-12 09:58 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/styles.module.css
> +  direction: row;
Fixed in https://github.com/safe-global/safe-homepage/pull/429/commits/9658bb02f36e06de80a4905f737e0018e4f65aea

2024-08-12 10:29 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +        <Typography variant="h5">1 square - ${squareRatio.toFixed(2)}B</Typography>
Exactly! I shared the wrong formatter

2024-08-12 10:32 UTC, DiogoSoaress approved these changes

2024-08-12 10:33 UTC, merged