fix(Dataroom): import Framer Motion's components on client-side
safe-global/safe-homepage pull request #436
Opened 2024-08-07 13:28 UTC by DiogoSoaress

## What it solves

Resolves #

## How this PR fixes it

2024-08-21 13:58 UTC, DiogoSoaress commented on src/components/DataRoom/AssetsSecured/SlidingContent.tsx
> +  const { width: viewportWidth } = useContainerSize(containerRef)
`useContainerSize` hook is executing the same function using the ResizeObserver Web API

2024-08-21 14:19 UTC, DiogoSoaress commented
I identified the repetition of the Framer Motion hook to track the scroll progress but addressed the refactor in a different [PR](https://github.com/safe-global/safe-homepage/pull/443) to keep this PR scope narrow

2024-09-02 07:44 UTC, iamacook requested changes
The new refs aren't being forwarded - the relative children need to also be wrapped in `forwardRef`.

2024-09-06 13:25 UTC, DiogoSoaress commented
> The new refs aren't being forwarded - the relative children need to also be wrapped in `forwardRef`.

Framer’s Motion `useScroll` is expecting to receive a `target?: RefObject$1<HTMLElement>;` instead of a `ForwardedRef<HTMLDivElement>` so I don't think that change is necessary.

2024-09-09 08:01 UTC, iamacook approved these changes

2024-09-09 12:09 UTC, merged